// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kawalees-home/CinematicDepth.tsx": () => import("../components/mockups/kawalees-home/CinematicDepth.tsx"),
  "./components/mockups/kawalees-home/RefinedClarity.tsx": () => import("../components/mockups/kawalees-home/RefinedClarity.tsx"),
  "./components/mockups/kawalees-join/VariationA.tsx": () => import("../components/mockups/kawalees-join/VariationA.tsx"),
  "./components/mockups/kawalees-join/VariationB.tsx": () => import("../components/mockups/kawalees-join/VariationB.tsx")
};
